package com.landray.kmss.dfm.ws.service.tims;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * IDfmEsbTimsServiceService service = new IDfmEsbTimsServiceService();
 * IDfmEsbTimsService portType = service.getIDfmEsbTimsServicePort();
 * portType.addOtherFlow(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "IDfmEsbTimsServiceService", targetNamespace = "http://tims.service.ws.dfm.kmss.landray.com/", wsdlLocation = "http://10.3.203.82/ekp/sys//webservice/dfmEsbTimsService?wsdl")
public class IDfmEsbTimsServiceService extends Service {

	private final static URL IDFMESBTIMSSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.landray.kmss.dfm.ws.service.tims.IDfmEsbTimsServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.landray.kmss.dfm.ws.service.tims.IDfmEsbTimsServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.3.203.82/ekp/sys//webservice/dfmEsbTimsService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://10.3.203.82/ekp/sys//webservice/dfmEsbTimsService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		IDFMESBTIMSSERVICESERVICE_WSDL_LOCATION = url;
	}

	public IDfmEsbTimsServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IDfmEsbTimsServiceService() {
		super(IDFMESBTIMSSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://tims.service.ws.dfm.kmss.landray.com/",
				"IDfmEsbTimsServiceService"));
	}

	/**
	 * 
	 * @return returns IDfmEsbTimsService
	 */
	@WebEndpoint(name = "IDfmEsbTimsServicePort")
	public IDfmEsbTimsService getIDfmEsbTimsServicePort() {
		return super.getPort(new QName(
				"http://tims.service.ws.dfm.kmss.landray.com/",
				"IDfmEsbTimsServicePort"), IDfmEsbTimsService.class);
	}

}
