package com.landray.kmss.dfm.ws.service.tims;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IDfmEsbTimsService", targetNamespace = "http://tims.service.ws.dfm.kmss.landray.com/")
public interface IDfmEsbTimsService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 * @throws Exception_Exception
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "addOtherFlow", targetNamespace = "http://tims.service.ws.dfm.kmss.landray.com/", className = "com.landray.kmss.dfm.ws.service.tims.AddOtherFlow")
	@ResponseWrapper(localName = "addOtherFlowResponse", targetNamespace = "http://tims.service.ws.dfm.kmss.landray.com/", className = "com.landray.kmss.dfm.ws.service.tims.AddOtherFlowResponse")
	public String addOtherFlow(
			@WebParam(name = "arg0", targetNamespace = "") String arg0)
			throws Exception_Exception;

}
