package com.dawnpro.rd.connector.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "EkpPutCncStateInfoPortType", targetNamespace = "http://service.connector.rd.dawnpro.com")
public interface EkpPutCncStateInfoPortType {

	/**
	 * 
	 * @param approvalOperName
	 * @param rejectDetail
	 * @param cncId
	 * @param costDetail
	 * @param actionId
	 * @param approvalIdea
	 * @param flowId
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.connector.rd.dawnpro.com")
	@RequestWrapper(localName = "putCncStateInfo", targetNamespace = "http://service.connector.rd.dawnpro.com", className = "com.dawnpro.rd.connector.service.PutCncStateInfo")
	@ResponseWrapper(localName = "putCncStateInfoResponse", targetNamespace = "http://service.connector.rd.dawnpro.com", className = "com.dawnpro.rd.connector.service.PutCncStateInfoResponse")
	public String putCncStateInfo(
			@WebParam(name = "cncId", targetNamespace = "http://service.connector.rd.dawnpro.com") String cncId,
			@WebParam(name = "flowId", targetNamespace = "http://service.connector.rd.dawnpro.com") String flowId,
			@WebParam(name = "actionId", targetNamespace = "http://service.connector.rd.dawnpro.com") String actionId,
			@WebParam(name = "approvalOperName", targetNamespace = "http://service.connector.rd.dawnpro.com") String approvalOperName,
			@WebParam(name = "approvalIdea", targetNamespace = "http://service.connector.rd.dawnpro.com") String approvalIdea,
			@WebParam(name = "rejectDetail", targetNamespace = "http://service.connector.rd.dawnpro.com") String rejectDetail,
			@WebParam(name = "costDetail", targetNamespace = "http://service.connector.rd.dawnpro.com") String costDetail);

}
