package com.dawnpro.rd.connector.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * EkpPutCncStateInfo service = new EkpPutCncStateInfo();
 * EkpPutCncStateInfoPortType portType = service.getEkpPutCncStateInfoHttpPort();
 * portType.putCncStateInfo(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "EkpPutCncStateInfo", targetNamespace = "http://service.connector.rd.dawnpro.com", wsdlLocation = "http://10.223.22.97:8180/ZPublicInterfaceFromEkp_CncState/ws/EkpPutCncStateInfo?wsdl")
public class EkpPutCncStateInfo extends Service {

	private final static URL EKPPUTCNCSTATEINFO_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.dawnpro.rd.connector.service.EkpPutCncStateInfo.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.dawnpro.rd.connector.service.EkpPutCncStateInfo.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"http://10.223.22.97:8180/ZPublicInterfaceFromEkp_CncState/ws/EkpPutCncStateInfo?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://10.223.22.97:8180/ZPublicInterfaceFromEkp_CncState/ws/EkpPutCncStateInfo?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		EKPPUTCNCSTATEINFO_WSDL_LOCATION = url;
	}

	public EkpPutCncStateInfo(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public EkpPutCncStateInfo() {
		super(EKPPUTCNCSTATEINFO_WSDL_LOCATION,
				new QName("http://service.connector.rd.dawnpro.com",
						"EkpPutCncStateInfo"));
	}

	/**
	 * 
	 * @return returns EkpPutCncStateInfoPortType
	 */
	@WebEndpoint(name = "EkpPutCncStateInfoHttpPort")
	public EkpPutCncStateInfoPortType getEkpPutCncStateInfoHttpPort() {
		return super
				.getPort(new QName("http://service.connector.rd.dawnpro.com",
						"EkpPutCncStateInfoHttpPort"),
						EkpPutCncStateInfoPortType.class);
	}

}
