package com.landray.kmss.third.ekp.java.oms.in.ehr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ISysSynchroGetOrgWebService", targetNamespace = "http://out.webservice.organization.sys.kmss.landray.com/")
public interface ISysSynchroGetOrgWebService {

	/**
	 * 
	 * @param arg0
	 * @return returns
	 *         com.landray.kmss.third.ekp.java.oms.in.ehr.SysSynchroOrgResult
	 * @throws Exception_Exception
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getUpdatedElements", targetNamespace = "http://out.webservice.organization.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.oms.in.ehr.GetUpdatedElements")
	@ResponseWrapper(localName = "getUpdatedElementsResponse", targetNamespace = "http://out.webservice.organization.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.oms.in.ehr.GetUpdatedElementsResponse")
	public SysSynchroOrgResult getUpdatedElements(
			@WebParam(name = "arg0", targetNamespace = "") SysSynchroGetOrgInfoContext arg0)
			throws Exception_Exception;

	/**
	 * 
	 * @param arg0
	 * @return returns
	 *         com.landray.kmss.third.ekp.java.oms.in.ehr.SysSynchroOrgResult
	 * @throws Exception_Exception
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getElementsBaseInfo", targetNamespace = "http://out.webservice.organization.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.oms.in.ehr.GetElementsBaseInfo")
	@ResponseWrapper(localName = "getElementsBaseInfoResponse", targetNamespace = "http://out.webservice.organization.sys.kmss.landray.com/", className = "com.landray.kmss.third.ekp.java.oms.in.ehr.GetElementsBaseInfoResponse")
	public SysSynchroOrgResult getElementsBaseInfo(
			@WebParam(name = "arg0", targetNamespace = "") SysSynchroGetOrgBaseInfoContext arg0)
			throws Exception_Exception;

}
